### ISSUE TITLE
add action for URL shortener

### ISSUE THREAD

**Issue by bendice** [joecks/clipboard-actions#11]
add the ability to shorten a URL in clipboard with a URL shortener service, at least a default one, or even better be able to configure the shortener of personal choice
(you can get Inspiration from the URLy Android app

**Comment by joecks** [comment]
Nice idea.
That would be a transformation action, which workflow would that follow:

copy an text with url ->  show a shorten url action -> goto shortener service website with short url?
or
copy an text with url ->  show a shorten url action -> do shortening in the background -> put it in the clipboard -> show a new notification with a shortened url  (so that you could use the shortened url in for instance share or paste)?

**Comment by bendice** [comment]
i would rather prefer the latter version.

- a copied URL triggers the visibility of the shortening action 
-> a click on the Action invokes the shortening in the background and possibly replaces the previous content of the clipboard
-> thereby the short URL can be shared through the existing share action or pasted into a text during Messaging e.g.

**Comment by bendice** [comment]
the configuration of the shortening service can be done in the app settings, this way you could support different service providers of which the user has to select his default shortener, most of them have apis and some of them require credentials for example
