### ISSUE TITLE
Clear Clipboard History

### ISSUE THREAD

**Issue by joecks** [joecks/clipboard-actions#16]
provide a way how to clear the clipboard history

**Comment by CodyToombs** [comment]
I'd add that there should also be a way to wipe individual items from history along with a method for wiping away everything.

Since most people would probably use either one or the other (clear singles or clear all), it might be possible to save some space on the UI by placing a single button and allowing it to be toggled with a setting.

**Comment by joecks** [comment]
In the first iteration I add the single delete function. Currently there is no persistence, then it might be interesting to have a wipe all option.
